name: build
on:
  pull_request:
jobs:
  test-bot:
    runs-on: linux-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Install ldid
        run: |-
          OLDPWD=$(pwd)
          apt-get update
          apt-get install git build-essential libplist-dev libssl-dev openssl qemu-user-binfmt
          cd /tmp
          git clone git://git.saurik.com/ldid.git
          cd ldid
          git submodule update --init
          gcc -I. -c -o lookup2.o lookup2.c
          g++ -std=c++11 -o ldid lookup2.o ldid.cpp -I. -lcrypto -lplist -lxml2
          sudo mv ldid /usr/local/bin
          cd $OLDPWD
      - name: Build bottles
        run: |-
          VERSION=v6.18.0
          mkdir -p workdir
          cd workdir
          curl -fsSLo pnpm.tar.gz https://github.com/pnpm/pnpm/archive/refs/tags/${VERSION}.tar.gz
          tar --strip-component 1 -xzf pnpm.tar.gz
          mkdir -p bootstrap
          curl -fsSLo bootstrap/pnpm-bootstrap.js https://get.pnpm.io/v6.14.js
          printf '#!/bin/sh\nnode '"$(pwd)"'/bootstrap/pnpm-bootstrap.js "$@"' > bootstrap/pnpm
          chmod a+x bootstrap/pnpm
          export PATH="$(pwd)/bootstrap:$PATH"
          pnpm install
          (
            cd packages/pnpm &&
            pnpm run compile
          )
          (
            cd packages/exe &&
            node_modules/.bin/pkg --target=macos-x64,macos-arm64,linuxstatic-x64 ../pnpm/dist/pnpm.cjs
          )

          bottle() {
            mkdir -p "$1/pnpm-exe/${VERSION#v}/bin" "$1/pnpm-exe/${VERSION#v}/.brew"
            cp "packages/exe/pnpm-$1" "$1/pnpm-exe/${VERSION#v}/bin/pnpm"
            cp ../Formula/pnpm-exe.rb "$1/pnpm-exe/${VERSION#v}/.brew"
            (
              cd "$1" &&
              gtar \
                --create \
                --numeric-owner \
                --format pax \
                --owner 0 \
                --group 0 \
                --sort name \
                --pax-option globexthdr.name=/GlobalHead.%n,exthdr.name=%d/PaxHeaders/%f,delete=atime,delete=ctime \
                --file "../pnpm-exe-${VERSION#v}.$2.bottle.tar.gz" \
                "pnpm-exe/${VERSION#v}"
            )
          }
          bottle macos-arm64 arm64_big_sur
          bottle macos-x64 big_sur
          bottle linuxstatic-x64 x86_64_linux

      - name: Upload bottles as artifact
        if: always() && github.event_name == 'pull_request'
        uses: actions/upload-artifact@main
        with:
          name: bottles
          path: '*.bottle.*'

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Set up git
        uses: Homebrew/actions/git-user-config@master

      - name: Pull bottles
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ github.token }}
          HOMEBREW_GITHUB_PACKAGES_TOKEN: ${{ github.token }}
          HOMEBREW_GITHUB_PACKAGES_USER: ${{ github.actor }}
          PULL_REQUEST: ${{ github.event.pull_request.number }}
        run: brew pr-pull --debug --tap=$GITHUB_REPOSITORY $PULL_REQUEST

      - name: Push commits
        uses: Homebrew/actions/git-try-push@master
        with:
          token: ${{ github.token }}
          branch: main
